#!/usr/sbin/nft -f

flush ruleset

define WAN_IF = eth0
define DEST_IP = 104.16.124.96

table ip nat {
	chain prerouting {
		type nat hook prerouting priority dstnat; policy accept;

		iifname $WAN_IF tcp dport 443 dnat to $DEST_IP:443
		iifname $WAN_IF udp dport 443 dnat to $DEST_IP:443
	}

	chain postrouting {
		type nat hook postrouting priority srcnat; policy accept;

		oifname $WAN_IF tcp dport 443 masquerade
		oifname $WAN_IF udp dport 443 masquerade
	}
}
