#!/usr/sbin/nft -f

flush ruleset

define WAN_IF = enp1s0
define DEST_IP = 104.16.124.96

table ip nat {
	chain prerouting {
		type nat hook prerouting priority dstnat; policy accept;

		iifname $WAN_IF tcp dport 443 dnat to $DEST_IP:443
		iifname $WAN_IF udp dport 443 dnat to $DEST_IP:443
	}

	chain postrouting {
		type nat hook postrouting priority srcnat; policy accept;

		# ct status dnat keeps this off Jool's v6->v4 traffic, which never hits our dnat rule
		oifname $WAN_IF ct status dnat tcp dport 443 masquerade to :1024-32767
		oifname $WAN_IF ct status dnat udp dport 443 masquerade to :1024-32767
	}
}
